---
name: golangci-lint

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

jobs:
  golangci-lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
            go-version-file: go.mod
            cache: false

      - name: Run go mod tidy
        run: |
          make godeps-update

      - name: Source build env variables
        run: |
          grep -v '^#' hack/build.env >> $GITHUB_ENV

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: ${{ env.GO_LINT_IMG_TAG }}
          args: "--timeout=5m"
